# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image with a compatible version
FROM python:3.12-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . .

# Install dependencies using the Python package manager
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir httpx==0.28.1 \
    && pip install --no-cache-dir mcp==1.1.2 \
    && pip install --no-cache-dir google-api-python-client==2.156.0 \
    && pip install --no-cache-dir google-auth-httplib2==0.2.0 \
    && pip install --no-cache-dir google-auth-oauthlib==1.2.1

# Expose port (if needed by the application, adjust if different)
EXPOSE 8080

# Set environment variables for credentials and tokens paths
# These should be adjusted as per the user's local configuration
ENV CREDS_FILE_PATH="/app/.google/client_creds.json"
ENV TOKEN_PATH="/app/.google/app_tokens.json"

# Run the MCP server
ENTRYPOINT ["python", "src/gmail/server.py", "--creds-file-path", "$CREDS_FILE_PATH", "--token-path", "$TOKEN_PATH"]
